# Generated by Django 2.1.3 on 2018-11-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0002_auto_20180519_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boda',
            name='Enamorado2',
        ),
    ]
