# Generated by Django 2.0.4 on 2018-05-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremoniaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fotos', models.BooleanField(default=False)),
                ('precio', models.BigIntegerField(default=0)),
                ('Boda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domain.Boda')),
                ('Lugar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='DecoracionCeremonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='Ceremonia/Decoracion')),
                ('precio', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Decoración',
                'verbose_name_plural': 'Decoraciones',
            },
        ),
        migrations.CreateModel(
            name='DecoracionCeremoniaCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField(default=0)),
                ('CeremoniaEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ceremonia.CeremoniaEvento')),
                ('Decoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ceremonia.DecoracionCeremonia')),
            ],
        ),
        migrations.CreateModel(
            name='Ministro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('catolica', 'Catolica'), ('civil', 'Civil')], max_length=50)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='Ceremonia/Ministros')),
                ('precio', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='Ceremonia/Musicas')),
                ('precio', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ceremoniaevento',
            name='Ministro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ceremonia.Ministro'),
        ),
        migrations.AddField(
            model_name='ceremoniaevento',
            name='Musica',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ceremonia.Musica'),
        ),
    ]
