# Generated by Django 2.0.4 on 2018-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='descripcion',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Alimento'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='descripcion',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Decoracion'),
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='descripcion',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Entretenimiento'),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
