# Generated by Django 2.1.3 on 2018-11-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0002_auto_20180519_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiestaevento',
            name='Fotos',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
