# Generated by Django 2.0.4 on 2018-05-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('precio', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ActividadCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Actividad')),
            ],
            options={
                'verbose_name': 'Actividad plan',
                'verbose_name_plural': 'Actividad planes',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('calificacion', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('precio', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.CreateModel(
            name='HotelCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Hotel')),
            ],
            options={
                'verbose_name': 'Hotel plan',
                'verbose_name_plural': 'Hotel planes',
            },
        ),
        migrations.CreateModel(
            name='LunaMielEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.BigIntegerField(default=0)),
                ('Boda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domain.Boda')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.AddField(
            model_name='hotelplan',
            name='Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Plan'),
        ),
        migrations.AddField(
            model_name='hotelcarrito',
            name='LunaMielEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.LunaMielEvento'),
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Plan'),
        ),
        migrations.AddField(
            model_name='actividadcarrito',
            name='LunaMielEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.LunaMielEvento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMiel.Plan'),
        ),
    ]
