# Generated by Django 2.0.4 on 2018-05-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMiel', '0002_auto_20180519_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='Plan',
        ),
        migrations.AddField(
            model_name='actividadcarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelcarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelplan',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='LunaMiel/Actividad'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='LunaMiel/Hotel'),
        ),
    ]
