# Generated by Django 2.0.4 on 2018-05-13 22:44

import Pareja.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoObjeto', models.CharField(max_length=50)),
                ('alquilado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('precio', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccesorioCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pareja.Accesorio')),
            ],
        ),
        migrations.CreateModel(
            name='Belleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquillaje', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('peinado', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/')),
                ('precio', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BellezaCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Belleza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pareja.Belleza')),
            ],
        ),
        migrations.CreateModel(
            name='Enamorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, validators=[Pareja.models.numeric_validator])),
                ('telefono', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('precio', models.BigIntegerField(default=0)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('tipo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixta')], default=None, max_length=50)),
                ('precio', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrendaCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enamorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pareja.Enamorado')),
                ('Prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pareja.Prenda')),
            ],
        ),
        migrations.AddField(
            model_name='bellezacarrito',
            name='Enamorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pareja.Enamorado'),
        ),
        migrations.AddField(
            model_name='accesoriocarrito',
            name='Enamorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pareja.Enamorado'),
        ),
    ]
