# Generated by Django 2.0.4 on 2018-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/Accesorio'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='belleza',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/Belleza'),
        ),
        migrations.AlterField(
            model_name='belleza',
            name='maquillaje',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='belleza',
            name='peinado',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/Prenda'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.CharField(max_length=250),
        ),
    ]
